site_name: Projeto Microservice
site_author: Gustavo Nicacio, Gabriel SOdré, Vitor Fengler
site_url: https://projeto-micro/microservices
repo_url: https://github.com/projeto-micro/projeto
repo_name: projeto-micro/projeto

theme:
  name: material
  palette:
    - scheme: default
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - media: "(prefers-color-scheme)"
      primary: grey
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      primary: grey
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.path
    - navigation.tracking
    - navigation.expand
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - minify:
      minify_html: true

extra_javascript:
  - https://unpkg.com/mathjax/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js

nav:
  - Home: index.md
  - Arquitetura: architecture.md
  - Microserviços:
    - Exchange API: services/exchange.md
    - Product API: services/product.md
    - Order API: services/order.md
  - Infraestrutura:
    - AWS: infraestrutura/aws.md
    - EKS: infraestrutura/eks.md
    - CI/CD: infraestrutura/cicd.md
  - Testes de Carga: load-testing.md
  - Bottlenecks: bottlenecks.md
  - Custos & SLA: costs.md
  - PaaS: paas.md