site_name: Store Project
site_author: Gustavo Nicacio, Gabriel Sodre, Vitor Fengler
site_url: https://projeto-micro.github.io/projeto
repo_url: https://github.com/projeto-micro/projeto
repo_name: projeto-micro/projeto
use_directory_urls: false

theme:
  name: material
  palette:
    - scheme: default
      primary: grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: grey
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.path
    - navigation.tracking
    - navigation.expand

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js

nav:
  - Home: index.md
  - Arquitetura: architecture.md
  - Microservicos:
      - Exchange API: services/exchange.md
      - Product API: services/product.md
      - Order API: services/order.md
  - Infraestrutura:
      - AWS: infraestrutura/aws.md
      - EKS: infraestrutura/eks.md
      - CI/CD: infraestrutura/cicd.md
  - Testes de Carga: load-testing.md
  - Bottlenecks: bottlenecks.md
  - Custos & SLA: costs.md
  - PaaS: paas.md
