
name: store-api

services:

  db:
    image: postgres:17
    hostname: db
    ports:
      - 5432:5432
    volumes:
      - ${VOLUME_DB}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-store}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-devpass}
      POSTGRES_DB: ${DB_NAME:-store}

  account:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    hostname: account
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_DB: ${DB_NAME:-store}
      DATABASE_USERNAME: ${DB_USER:-store}
      DATABASE_PASSWORD: ${DB_PASSWORD:-devpass}
    deploy:
      replicas: 1
    depends_on:
      - db

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    hostname: auth
    deploy:
      replicas: 1
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-jYCiN0YPiaBP53bGJi/kjfw79HW7xnBu9UPoD/QFFAE=}
      JWT_HTTP_ONLY: ${JWT_HTTP_ONLY:-true}
    depends_on:
      - account

  exchange:
    build:
      context: ./exchange-service
      dockerfile: Dockerfile
    hostname: exchange
    environment:
      EXCHANGE_PROVIDER_URL: ${EXCHANGE_PROVIDER_URL:-https://economia.awesomeapi.com.br/json/last/{from_currency}-{to_currency}}
      EXCHANGE_CACHE_TTL_SECONDS: ${EXCHANGE_CACHE_TTL_SECONDS:-60}
      EXCHANGE_REQUEST_TIMEOUT_SECONDS: ${EXCHANGE_REQUEST_TIMEOUT_SECONDS:-5}
    deploy:
      replicas: 1

  gateway:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    hostname: gateway
    environment:
      CORS_ALLOWED_CREDENTIALS: ${CORS_ALLOWED_CREDENTIALS:-true}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-*}
    ports:
      - 8080:8080
    depends_on:
      - auth
      - account
      - exchange

  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - ${SETUP}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ${SETUP}/grafana:/var/lib/grafana
      - ${SETUP}/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
